config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :topics
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      get :activation
    end
  end

  resources :sessions

  root "questions#index"
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :topics
  # TODO Remeber to remove orphens 
  has_one_attached :attachment

  has_many :answers

  validates :title, :content, presence: true
  validate :attachment_can_only_be_pdf

  def attachment_can_only_be_pdf
    if attachment.nil? && attachment.content_type != "application/pdf"
      errors.add(:attachment, "Only pdf can be used")
    end 
  end

  def assign_tags(all_topic_ids)
    ids = all_topic_ids.reject(&:empty?).map(&:strip)
    ids.each do |id|
      self.topics << Topic.find(id)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
    @all_topics = Topic.all.map { |topic| [topic.name, topic.id] }
  end

  def edit
  end

  def create
    @question = Question.new(question_params.merge(user_id: current_user.id))
    if @question.save
      @question.assign_tags(params[:question][:tags])
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :content, :attachment, :tags)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_form.html.erb
<%= form_with(model: answer, local: true, class: 'custom-answer-form') do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>
      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :question_id, value: question.id %>
  </div>

  <div class="field answer-field-container">
    <%= form.text_area :content, placeholder: 'Write your answers here' %>
  </div>

  <div class="actions">
    <%= form.submit "Answer!!" %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :attachment, "Optional PDF attachment" %>
    <%= form.file_field :attachment %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.select :tags, all_topics, { include_blank: false }, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="ask-a-question">
  <p>Asking a question is healthy for brain, go ahead and give it a try</p>
  <h3><%= link_to "Have something in mind ?", new_question_path %></h3>
</div>

<% @questions.each do |question| %>
  <div class="question-container">
    <h3 class="title"><%= link_to question.title, question_path(question.id) %></h3>
    <p class="author">Posted by <%= User.find(question.user_id).name %></p>
    <div class="attachment">
      <% if question.attachment.attached? %>
        <%= link_to image_tag(question.attachment.preview(resize: "1080x1080")), 
           question_path(question.id) %> 
      <% end %>
    </div>
    <p class="content"><%= question.content %></p>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question, all_topics: @all_topics %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="question-show-page">
  <div class="title">
    <%= @question.title %>
  </div>

  <div class="content">
    <%= @question.content %>
  </div>

  <p class="author">Posted by <%= User.find(@question.user_id).name %></p>
  <p>Attachment :-</p>
  <p>
    <% if @question.attachment.attached? %>
      <%= link_to image_tag(@question.attachment.preview(resize: "360x240")), 
        rails_blob_path(@question.attachment, disposition: "attachment") %>
    <% end %>
  </p>

  <h1><strong>Answers</strong></h1>
  <hr />
  
  <ul class="answers-list">
  <% @question.answers.each do |answer| %>
    <li> <%= answer.content %></li>
  <% end %>
  </ul>

  <% if logged_in? %>
    <div class="answer-form">
      <%= render 'answer_form', answer: @answer, question: @question %>
    </div>
  <% end %>
</div>