config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :topics
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      get :activation
    end
  end

  resources :sessions

  root "questions#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :detail, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :interests
  has_many :topics, through: :interests
  has_many :answers

  accepts_nested_attributes_for :detail, allow_destroy: true, update_only: true,
                                reject_if: :all_blank

  validates :name, :email, presence: true
  validates :password, :password_confirmation, presence: true, allow_blank: true
  validates :email, uniqueness: true

  def activate
    self.active = true
    self.activation_token = nil
    save!(validate: false)
  end

  def assign_interests(all_topic_ids)
    ids = all_topic_ids.reject {|_| _.empty? }.map { |_| _.strip }
    ids.each do |id|
      self.topics << Topic.find(id)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:edit, :update]
  before_action :authenticate_admin, only: [:show, :index, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
    @all_topics = Topic.all.map { |topic| [topic.name, topic.id] }
    @user.build_detail
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.activation_token = SecureRandom.urlsafe_base64.to_s
    if @user.save
      @user.assign_interests(params[:user][:interests])
      UserMailer.user_activation_email(@user).deliver_now
      redirect_to login_path, 
          notice: 'User was successfully created. Please confirm with email to activate user'
    else
      @all_topics = Topic.all.map { |topic| [topic.name, topic.id] }
      render :new
    end
  end

  def activation
    user = User.find_by_activation_token(params[:id])
    if user
      user.activate
      flash[:success] = "Welcome to the Quora Clone!, Please login to continue."
      redirect_to root_url
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def update
    if @user.update(user_params)
        redirect_to edit_user_path(@user.id), notice: 'User was successfully updated.'
    else
        render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :interests,
        detail_attributes: [:avatar])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.fields_for :detail do |detail| %>
      <%= label_tag :avatar, "Profile Picture"  %>
      <% if user.detail.avatar.attached? && user.detail.avatar.image? %>
        <%= image_tag user.detail.avatar.variant(resize: "130x130"),  id: "avatar-tag", 
            class: "avatar_image" %>  
      <% else %>
        <%= image_tag "", id: "avatar-tag", class: "avatar_image" %>
      <% end %>
      <%= detail.file_field :avatar, id: "avatar" %>
    <% end %>
  </div>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form_new.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.fields_for :detail do |detail| %>
      <%= label_tag :avatar, "Choose a profile picture"  %>
      <%= image_tag "", id: "avatar-tag", class: "avatar_image" %>
      <%= detail.file_field :avatar, id: "avatar" %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

    <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :interests %>
    <%= form.select :interests, all_topics, { include_blank: false }, { multiple: true,  
        class: "select-interests" } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="user-profile">
  <h3>User Profile</h3>
  <%= render 'form_edit', user: @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= user.active %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="sign-up">
  <h3>Sign Up Form</h3>

  <%= render 'form_new', user: @user, all_topics: @all_topics %>
</div> 

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>