config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :topics
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    member do
      get :activation
    end
  end

  resources :sessions

  root "questions#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar">
        <div class="nav-left-section">
          <%= link_to "HOME", root_path %>
        </div>
        <div class="nav-right-section">
          <% if logged_in? %>
            <%= link_to current_user.name, edit_user_path(current_user.id), class: 'user-name' %>
            <%= link_to "Log Out", logout_path %>
          <% else %>
            <%= link_to "Login", login_path %>
            <%= link_to "Sign Up", signup_path %>
          <% end %>
        </div>
      </nav>

      <div class="content-container">
      
        <% flash.each do |key, value| %>
            <p id='<%= key %>'><%= value %></p>
        <% end %>

        <%= yield %>
      
      </div>

    </div>
  </body>
</html>